version: '3.7'
services:
  server:
    #build: ./server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    #image: grpc-server:latest
    container_name: grpc-server
    platform: linux/x86_64
    volumes:
      - './go.mod:/go/src/go.mod'
      - './go.sum:/go/src/go.sum'
      - './server:/go/src/server'
      - './pb:/go/src/pb'
    expose:
      - 50051
    command:
      - '/main'
  envoy:
    image: envoyproxy/envoy:dev
    volumes:
      - './envoy:/etc/envoy'
      - './pb:/etc/pb'
    expose:
      - 51052
    ports:
      - 51052:51051
    links:
      - server
volumes:
  data:
    driver: 'local'
